(display "ze: loaded plugin file-header.scm") (newline)

(define (insert-file-header)
  (let* ((ft (or (get-filetype) "unknown"))
         (fn (or (get-filename) "(unsaved)"))
         (ts (begin (insert-text! "") (buffer->string)))) ; dummy to ensure API loaded
    (insert-line! 0 (string-append ";; File: " fn))
    (insert-line! 1 (string-append ";; Type: " ft))
    (insert-line! 2 (string-append ";; Generated by ze plugin"))
    (set-cursor! 0 3)
    (set-editor-status "Inserted header")))

;; Bind to C-, (overrides backspace alias in some contexts; demo only)
(bind-key "C-," insert-file-header)


