name: Build Doxygen into docs/api

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Build Doxygen
        run: doxygen Doxyfile
      - name: Commit docs/api (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/api
          git commit -m "Update Doxygen docs [skip ci]" || echo "No changes"
          git push

